name: Strike the Dagger
on:
  workflow_dispatch:
  push:
    branches: 
      - main

jobs:

  build:

    name: build
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Add problem matcher
        run: |
          echo "::add-matcher::.github/workflows/matchers/markdownlint.json"

      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"

      - name: Install Dagger CLI
        run: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }

      - name: Run Dagger pipeline
        run: dagger run go run main.go