on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Version and create GitHub release

jobs:
  release-please:
    name: "Create release with Release Please"
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@ca6063f4ed81b55db15b8c42d1b6f7925866342d # v3.7.11
        with:
          release-type: go
          package-name: brandish
